### ISSUE TITLE
addObjectToWorld - forEachObject

### ISSUE THREAD

**Issue by dev-zetta** [lance-gg/lance#105]
There should be possibility to exit the loop. Once the object is found, e.g. the return is true, it should quit the iteration.

https://github.com/lance-gg/lance/blob/f38918d332eb5ddad691e4b30b20728f25e967d9/src/GameEngine.js#L213

**Comment by namel** [comment]
yes, we need a function which scans the objects and returns the first one it found based on a test.  however the **serverCopyArrived** is a very rare case, where the server object was received before the client had the chance to create the shadow object.  It can only happen when the client and server are running on the same server.

**Comment by dev-zetta** [comment]
No, you actually only need to return false, once the object is found, ie:
```javascript
            this.world.forEachObject((id, o) => {
                if (o.hasOwnProperty('inputId') && o.inputId === object.inputId) {
                    serverCopyArrived = true;
                    return false;
                 }
            });
```

So it stops the iteration.

**Comment by namel** [comment]
cool. I didn't remember that `forEachObject` can exit early.  Fixed in develop.

**Comment by lifeiscontent** [comment]
@dev-zetta where is `inputId` set on a GameObject? I don't see It being used anywhere.
