### ISSUE TITLE
Switch to FlatBuffers serializer

### ISSUE THREAD

**Issue by dev-zetta** [lance-gg/lance#108]
Hello everyone,

I just went thru the Serializer.js. It would be much practical and performant to use FlatBuffers instead of that custom serializer implementation.

Have you considered that? 

https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html

**Comment by OpherV** [comment]
This is very interesting - I wasn't aware of this project. Thanks for the find!
I see potential in using something like this for the next major version of Lance

**Comment by OpherV** [comment]
Also - not an issue so I'm closing

**Comment by namel** [comment]
This is interesting.  I like that you can use it without unpacking (removes thousands of temporary objects per second), and that it also supports an un-enforced dynamic schema.  Basically game developers could skip the netschema definition phase, until they actually need the extra performance.
