### ISSUE TITLE
Idk what's wrong with starting 

### ISSUE THREAD

**Issue by DimaValetsky** [lance-gg/lance#116]
![изображение](https://user-images.githubusercontent.com/48615297/56292882-b2f16600-6130-11e9-80ad-e844bf8ac69e.png)
I get this every time when i try to start game
error is in lance-boilerplate@4.0.0 start: `node dist-server/main.js`
help pls

**Comment by namel** [comment]
I see you are on windows.  I just ran the following steps:

```
git clone git@github.com:lance-gg/tinygames.git
cd tinygames
cd boilerplate
npm install
npm start
```

and I don't see the error above.  What steps did you use to reproduce this?

**Comment by DimaValetsky** [comment]
Here we go:
![изображение](https://user-images.githubusercontent.com/48615297/56469037-f56eb780-643c-11e9-804b-fa9689713afe.png)
I'll do the same
1. CLoned
![изображение](https://user-images.githubusercontent.com/48615297/56469123-0d930680-643e-11e9-9d34-674ad9b35291.png)
2. chose directory
![изображение](https://user-images.githubusercontent.com/48615297/56469128-2e5b5c00-643e-11e9-8306-37c9c59cf18f.png)
3. installed npm
![изображение](https://user-images.githubusercontent.com/48615297/56469138-564abf80-643e-11e9-8088-8ecfbdd91c83.png)
Hello there, lots of errors
![изображение](https://user-images.githubusercontent.com/48615297/56469169-c22d2800-643e-11e9-919a-fc87448ecd5a.png)
![изображение](https://user-images.githubusercontent.com/48615297/56469172-d2450780-643e-11e9-9dbc-35243e72241d.png)

**Comment by namel** [comment]
ok - I see the problem in the output: babel-config is still a softlink.  I have a fix which should be pushed soon

**Comment by namel** [comment]
@DimaValetsky please try again with the latest build

**Comment by DimaValetsky** [comment]
![изображение](https://user-images.githubusercontent.com/48615297/56520754-a4021d80-654d-11e9-87f5-296946e6e77d.png)
Yeah! It's working!!!
Is it good too much "player scored?"
![изображение](https://user-images.githubusercontent.com/48615297/56521023-d0b63500-654d-11e9-9370-162eba9e093d.png)
I had some problems with vulnerabilities, but audit fix fixed them

**Comment by namel** [comment]
you can ignore the "player scored" message.  it's just playing out the game even though no one is connected and moving the paddles.
