### ISSUE TITLE
My First Game: Pong tutorial is missing imports

### ISSUE THREAD

**Issue by JonCStout** [lance-gg/lance#126]
The website tutorial is missing imports for TwoVector and KeyboardControls.  These are present in the pre-made pong folder, but not in the web walk-through:
http://docs.lance.gg/tutorial-MyFirstGame.html

**Comment by mreinstein** [comment]
this is a duplicate of https://github.com/lance-gg/lance/issues/126 we should close in favor of that one. Since that's the repo that actually has this code.
