### ISSUE TITLE
Serializer causes a crash if netScheme has a string

### ISSUE THREAD

**Issue by Pro1d** [lance-gg/lance#133]
I created a DynamicObject that contains a STRING netscheme attribute.
```import { BaseTypes, DynamicObject } from 'lance-gg';
export default class MyObject extends DynamicObject {
  static get netScheme() {
    return Object.assign({
      text: { type: BaseTypes.TYPES.STRING }
    }, super.netScheme);
  }

  constructor(gameEngine, options, props) {
    super(gameEngine, options, props);
    this.text = "???";
  }

  syncTo(other) {
    super.syncTo(other);
    this.text = other.text.clone();
  }
}
```
When I add this object to the world (gameEngine.addObjectToWorld()) from a my own ServerEngine class, it produces an error at run time in Serializer.writeDataView() due to this STRING attribute:
`TypeError: Cannot read property 'length' of undefined`, at the file/line: https://github.com/lance-gg/lance/blob/master/src/serialize/Serializer.js#L104

The code run correctly, if I change the type of the attribute to a number type.

Note: it seems that there is a similar problem with LIST attribute.

**Comment by Pro1d** [comment]
The error was mine, I did something wrong in my code (I am quite new to javascript). Sorry for the noise :pray: 

BTW, Excellent library! Good job :)

**Comment by namel** [comment]
thanks!
