### ISSUE TITLE
Is lance being actively developed?

### ISSUE THREAD

**Issue by raymondji** [lance-gg/lance#140]
(Apologies if this isn't the right place to ask!)

I really liked the documentation for this project (thank you for sharing the very helpful theory!) and was excited to give it a try, but noticed there hasn't been much activity in the github project lately. Just wanted to check if there are plans to keep developing the project. 

Thanks for all the great work so far!

**Comment by namel** [comment]
Lance is maintained, though not actively developed. So security vulnerabilities, and generated pull requests from github are handled.  But no new features are being developed.

**Comment by raymondji** [comment]
Gotcha, thank you!
