### ISSUE TITLE
Automated Cloud Deployment

### ISSUE THREAD

**Issue by namel** [lance-gg/lance#35]
This is a feature request.

Request for an automated cloud deployment, where game developers can provide links to their game repository in github, and game servers are automatically deployed, monitored, load-balanced, and statistics are collected.

**Comment by smokku** [comment]
I don't believe this feature belongs to this library.
This is orthogonal to the networking layer. There are companies building a whole business around the requested feature set.

**Comment by namel** [comment]
agreed
