### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by narrowfail** [lance-gg/lance#36]
Hello, testing the game engine in diverse network condition and found out that when the client can't keep up with the server, It starts leaking memory. I found this while playing "spaaace" game with a latency > 350 ms. I started shooting all over the screen and latency + memory started growing until the window hanged.
I think it has to do with the extrapolation and the sync.

Regards,
Guillermo

**Comment by namel** [comment]
hi - which version of spaaace were you running?  master branch or dev branch?
The current version running on http://spaaace.herokuapp.com/ is the master branch.

**Comment by narrowfail** [comment]
Right now and old version: https://github.com/OpherV/spaaace/commit/240d3ec3321d5a5e8b751f34b6be7f0bcbbccb1d

**Comment by tangmi** [comment]
Hi all, I'm the developer of [tangmi/node-gameloop](https://github.com/tangmi/node-gameloop) and it seems I accidentally introduced a memory leak from a pull request in npm version `0.1.1`. I believe I have resolved it in npm version `0.1.4`, so an `npm update node-gameloop` should fix it.

Alternately you can revert back to `0.1.0` to get the version before the leak.

Sorry if this has caused any trouble!

**Comment by namel** [comment]
Since there have been some significant changes since that level, including one memory leak (independent the `node-gameloop` fix), I suggest that we attempt to recreate this on the latest master level when it's ready.  Should come out this week or early next week.

**Comment by OpherV** [comment]
@narrowfail Do you still see the memory leak with the latest version?
