### ISSUE TITLE
GameEngine double process Input on the client side

### ISSUE THREAD

**Issue by shenzhuxi** [lance-gg/lance#43]
I followed the Pong game and set the object position in processInput in GameEngine like this: 
```
    processInput(inputData, playerId) {
        super.processInput(inputData, playerId);
        console.log(`player ${playerId} pressed ${inputData.input}`);
        let player = this.world.getPlayerObject(playerId);
        if (player) {
            switch(inputData.input) {
                case "e":
                    player.position.z -= 1;
                    break;
                case "d":
                    player.position.z += 1;
                    break;
                case "s":
                    player.position.x -= 1;
                    break;
                case "f":
                    player.position.x += 1;
                    break;
                case "w":
                    break;
                case "q":
                    break;
                default:
                    break;
            }
            console.log(inputData, player.position);
        }
    }
```
The player's client side log showed different player.position from the server and other clients. The GameEngine seems double processed.

**Comment by namel** [comment]
Can you provide more detail?
I'm guessing you want the paddle to move sideways?
Are you running in extrapolate mode or interpolate? what are you bending parameters?
Maybe you can show bits of the traces which you think are incorrect.  They are supposed
to be different in many scenarios.

in the tutorial pong, `processInput()` looks like this (there is no z-component in 2D games).
Updating the x-position as well should work.

```javascript
    processInput(inputData, playerId) {

        super.processInput(inputData, playerId);

        // get the player paddle tied to the player socket
        let playerPaddle = this.world.getPlayerObject(playerId);
        if (playerPaddle) {
            if (inputData.input === 'up') {
                playerPaddle.position.y -= 5;
            } else if (inputData.input === 'down') {
                playerPaddle.position.y += 5;
            }
        }
    }
```

**Comment by shenzhuxi** [comment]
'm using the same settings as https://github.com/lance-gg/spaaace/blob/629abdf7a4723909b7c92b848dc70084712ac8ad/src/client/clientEntryPoint.js. 

I'm using PhysicalObject. 
```
class PlayerAvatar extends PhysicalObject {
    constructor(id, position, velocity, quaternion, angularVelocity) {
        position = new ThreeVector(0, 10, 0);
        super(id, position, velocity, quaternion, angularVelocity);
        this.class = PlayerAvatar;
        this.physicsObj = {
            position: this.position,
            velocity: this.position,
            quaternion: this.quaternion,
            angularVelocity: this.angularVelocity
        };
    }
    onAddToWorld(gameEngine) {
        if (gameEngine.renderer) {
        }
    }
}
```
Since I'm only trying to sync the position data, I think it should work as DynamicObject. 

http://localhost:3000/?sync=extrapolate `console.log(inputData, player.position);` 
**Server side:** 
{ messageIndex: 190000,
  step: 56873,
  input: 's',
  options: { isDown: true } } ThreeVector { x: -1, y: 10, z: 0 }
**Player Client side:** 
Object {messageIndex: 190000, step: 56873, input: "s", options: Object}input: "s"messageIndex: 190000options: Objectstep: 56873__proto__: Object ThreeVector {x: -2, y: 10, z: 0}
**Other Clients side:** 
Have the same position as the server

http://localhost:3000/?sync=interpolate `console.log(inputData, player.position);` 
**Server side:**
{ messageIndex: 140002,
  step: 13330,
  input: 's',
  options: { isDown: true } } ThreeVector { x: -1, y: 10, z: 0 }
**All Clients side:** 
No output

http://localhost:3000/?sync=interpolate `console.log(inputData, player.position);` 
**Server side:**
{ messageIndex: 140002,
  step: 13330,
  input: 's',
  options: { isDown: true } } ThreeVector { x: -1, y: 10, z: 0 }
**All Client sides:** 
No output

framesync same as interpolate

**Comment by namel** [comment]
I see.  It's actually expected that the local client can be ahead of the server *for local objects only*.
Which physics engine are you using?

BTW, let's have this conversation on the lance.gg slack channel instead of github.
You can auto-join our slack channel here: http://slack.lance.gg/
