### ISSUE TITLE
version number on npm

### ISSUE THREAD

**Issue by shenzhuxi** [lance-gg/lance#44]
It's 1.0.4 on https://www.npmjs.com/package/lance-gg while r1.0.0 on github, and the codes are different. 
Which release is recommended? 
Thanks.

**Comment by namel** [comment]
the version number is in the form `<major>.<minor>.<patch>`
so you should always take the latest patch (in this case patch 4) because
a patch is a fix, not a change in API.

you can read about this standard it's called [semver](http://semver.org/).

**Comment by shenzhuxi** [comment]
I mean that the version number should match the release version number. The git tags shouldn't be less than the release number. People always assume the master branch is the latest code.

**Comment by namel** [comment]
Good point.  There should be a git tag for each published release.
