### ISSUE TITLE
[Feature Request] Provide Client Side Library

### ISSUE THREAD

**Issue by Jared-Sprague** [lance-gg/lance#52]
Hello!
This library is exactly what we've been looking,  but it's lacking one thing that is preventing us from using it:  An stand-alone client library.

We started using it for a recent game jam but had to abandon it when we realized that it assumes you are using browserfy.   Our projects use a build-less environment and are specifically designed not to use browserfy, so we can't use this library unless we completely change our build process.

All we need to be able to use Lance is a client library that we could include with a <script> tag.  This is standard for many other javascript libraries, like [socket.io](https://socket.io/docs/):

Like so:

    <script src="/socket.io/socket.io.js"></script>

Lance Client Example:

    <script src="/js/lance-client.js"><script>

Lance Server Example

    const ServerEngine = require('lance-gg').ServerEngine;

If you could provide a client side library that could be included with a script tag, then we could start using Lance and that would AWESOME!

**Comment by Jared-Sprague** [comment]
Also just wanted to mention,  I'm not suggesting replacing the current way of including the client classes with require(),   just making this an option for those of us with build-less environments.

**Comment by namel** [comment]
This request made me think about the simpler "trusted" use-case, where the server completely trusts the clients, and then there is no server code at all, just client-side code.

I think your feature request is part of that bigger feature.  Currently Lance assumes the entire code runs both on the client and the server, so it depends on package managers to wrap up the same code twice.  But as you pointed out, a passive "echo" server is an important use case.  And in that scenario `lance-client.min.js` would be a nice way to use it.

**Comment by Jared-Sprague** [comment]
@namel I love the idea of having a lance-client.js (non-minified for development) and lance-client.min.js  so we could start using this library in our games!  Any plan to build these?

**Comment by namel** [comment]
@Jared-Sprague I started working on this last week.  I think it's an important feature and I'm counting on you to beta-test it ;)

**Comment by Inateno** [comment]
required for me too.
I have an engine featuring all client stuff and would like a client "plugin" only for dealing with online stuff (as I'm doing usually when I'm doing a server from scratch).

In any case I'm definitively interested in this project, didn't had the courage to launch one, so I'll try few things to make it match my engine.

**Comment by Jared-Sprague** [comment]
@namel Hey just checking in,  are you guys still working on this project?

**Comment by namel** [comment]
Hi. The answer is both yes and no. I actually implemented a small prototype of scriptable Lance, and tried it out on pong. The result was not good because the api had to be rewritten completely, and a new set of docs would have to be written up for this embedded mode. So what we want to do instead is set up a “single file” mode, where you only need to extend the GameEngine class and you can rely on events for other things like rendering and server/client actions. This makes it possible to write simple games in a single file.

**Comment by kanecko** [comment]
@namel Hello there. What's the status report on this?

**Comment by namel** [comment]
I created a sample implementation 1-file game.  The entire game is implemented in a single javascript file, which runs both on the server and the client.  This demo is a new repository: https://github.com/lance-gg/tinygame
