### ISSUE TITLE
wrong link in a tutorial

### ISSUE THREAD

**Issue by Xyexs** [lance-gg/lance#55]
At http://docs.lance.gg/develop/tutorial-MyFirstGame.html, there is an alternative (almost at the bottom of the page) to simply fetch pong from git. It looks something like this:

> 
> NOTE: If you prefer to get a clean working copy, you can run:
> ```
> 
> git clone https://github.com/lance-gg/lancegame.git pong
> cd pong
> git checkout pong
> yarn install
> ```

https://github.com/lance-gg/lancegame.git should probably be https://github.com/lance-gg/netpong

**Comment by OpherV** [comment]
Thanks for this - we're doing a refactor of the docs for Lance V2 and this will be addressed
