### ISSUE TITLE
[Feature / Question] React-VR

### ISSUE THREAD

**Issue by jgwinner** [lance-gg/lance#62]
Does Lance support React-VR?

Thanks! It looks fascinating - read the article in MSDN magazine :)

**Comment by OpherV** [comment]
I haven't played with React-VR - so I don't know what that entails.
It does support [A-Frame](https://aframe.io/), and in fact our [Sprocket League demo](http://sprocketleague.lance.gg/) is based on it. I think A-Frame can work with React as well - so maybe? :)
