### ISSUE TITLE
Exist any demo with Phaser?

### ISSUE THREAD

**Issue by jdnichollsc** [lance-gg/lance#63]
Hi guys,
Exist any example with Phaser Framework?

Thanks in advance, Nicholls

**Comment by OpherV** [comment]
Hi @jdnichollsc unfortunately no,
Please have a look at this:
https://stackoverflow.com/questions/44085045/can-i-make-a-multiplayer-phaser-game-using-lance

**Comment by iamchristopher** [comment]
@OpherV Have you had a chance to take a look at Phaser v3 since answering that question? Wondering if the integration you alluded to has materialized in some way.

**Comment by jdnichollsc** [comment]
Please, don't close this item, we can work together in an implementation. Currently, I'm creating a template using ES2015 from the server and from the client with Phaser using socket.io, we can evaluate and create a prototype, or maybe using the new version of Phaser! 👍 

Let me know what you think

**Comment by Nodragem** [comment]
What about Phaser 3?

**Comment by jdnichollsc** [comment]
@OpherV Can we check this issue for Phaser 3 integration? :)
