### ISSUE TITLE
How do I go about implementing an external physics engine.

### ISSUE THREAD

**Issue by AskingQuestions** [lance-gg/lance#74]
I just need some pointers on where and how I should add a physics engine(Matter.js).

I got interpolation with matter js to work(I simply extended physics engine and updated the engine using step), however I think I might be doing the position, velocity, angle updating wrong.

Here is a GameObject snipet:

``` Javascript
class MyGameObject extends DynamicObject {
	constructor(id) {
		super(id);
		this.position.set(0, 0);
		this.class = GameObject;
	}

	onAddToWorld(gameEngine) {
		if (gameEngine.physicsEngine) {
                      //Add body to matter and keep track of it using a reference.
                      this.matter = ...;
		}
	}

	draw(ctx) {
		ctx.fillRect(this.position.x-5, this.position.y-5, 10, 10); //Simple test
	}

	syncTo(other, options) {
		super.syncTo(other);

		if (this.matter) //If this has a matter body reference
			this.refreshToPhysics();
	}

	bendToCurrent(original, bending, worldSettings, isLocal, bendingIncrements) {
		super.bendToCurrent(original, bending, worldSettings, isLocal, bendingIncrements);

		if (this.matter)
			this.refreshToPhysics();
	}

	refreshFromPhysics() { //Note: This is called in the GameEngine::step() (I loop over all objects)
		if (this.matter) {
			this.position.set(this.matter.position.x, this.matter.position.y);
			this.velocity.set(this.matter.velocity.x, this.matter.velocity.y);
			this.angle = this.matter.angle;
		}
	}

	refreshToPhysics() {
		Matter.Body.setPosition(this.matter, this.position);
		this.matter.velocity = this.velocity;
		this.matter.angle = this.angle;
	}

	step () {
		super.step();

		this.refreshFromPhysics(); //This is not needed since its called from GameEngine.
	}
}
```

This code works but when I have over 200 objects(simple 10x7 rectangles) the game freezes(Im not sure if lance stops sending or if the packet size is too large or etc.). The physics engine when run locally can handle well over that amount.

I then tried using extrapolation:
* with 200 objects the step takes 5s and eventually freezes.
* with 10 objects the physics is out of sync for clients.

Does the physics engine need to be deterministic?
I have looked at other PhysicsEngine implementations (Cannon, etc) and see no trace of GameObject.position updatin.

I have not yet tested lance without physics with over 200 objects, but I assume the freezing is my fault and not lance's.

If you need any more info please ask(Im sure if left something out)

Thank you.

**Comment by namel** [comment]
Hi,

That's pretty cool.  200 objects is actually quite high for lance, I don't think we've ever experimented with that many objects, so you may well have run into a limit which I am unfamiliar with and needs digging into.

The tougher problem though is that **DynamicObject** is designed specifically for the **SimplePhysicsEngine**, and you may not be able to inherit from it.  A better way to start working on matter.js is to write a different class which inherits directly from **GameObject**, and is implemented in the style of **PhysicalObject**.  You could call it **PhysicalObject2D**.

In this newer pattern which we used in **PhysicalObject**, each _game object_ has a corresponding _physical asset_ inside the physics engine, which it calls **this.physicsObj**.  The physics engine is responsible for maintaining the position, orientation, velocity, and angular velocity of the **physicsObj**.  `refreshFromPhysics()` and `refreshToPhysics()` are methods of the game object, exactly as you wrote them.  And in this scenario, the physics engine (matter) should update the physical asset, and `refreshFromPhysics()` will be called to collect the new position, orientation, velocity, and angular velocity values.

The physics engine does not need to be deterministic.  The client and server values are expected to diverge, and the bending algorithm should be able to adjust the client values back to the server values asymptotically.

The only other comment is that you should be working with the develop branch of lance if possible.  Please join our slack channel to keep us up to date on your progress.

**Comment by AskingQuestions** [comment]
I will have to do some more profiling on lance objects, and look into the 5s step(I saw that the bulk of the 5s was taken up by an `indexOf` call?)

Another question, does lance only send objects to the client if they have changed, or does it always send everything?

Thank you so much for your time.

**Comment by kanecko** [comment]
@namel you say that "200 objects is actually quite high for lance". Did you mean that in the context of using a physics engine, or in general?

**Comment by namel** [comment]
Closing this one, PhysicalObject2D now exists in the develop branch

**Comment by josiahbryan** [comment]
@namel @AskingQuestions  - did you ever get MatterJS integrated with Lance? I'm using MatterJs client-side, but I'd love to use Lance with it...

**Comment by namel** [comment]
Not integrated at the moment.  Are there any specific features which MatterJS has, and P2 doesn't?  Or is it just for convenience?

**Comment by AskingQuestions** [comment]
> @namel @AskingQuestions - did you ever get MatterJS integrated with Lance? I'm using MatterJs client-side, but I'd love to use Lance with it...

I had it working, but the performance did not suit my needs. However, if you're not stressing the network too much MatterJS is great (I don't think I tried more advanced objects like cloth, or soft bodies.)

I might be able to dig up the code and post it here if you want. (It was a year ago so things could be broken.)

**Comment by josiahbryan** [comment]
@namel @AskingQuestions  - thanks for the input, gents. @namel  - more the "cost of conversion" - doing a basic game, and hope to add "multiplayer" to http://kpxtest.surge.sh/ - just a silly little blocks game. Not worth my time to convert it right now to another physics engine, not to mention, an entirely new build stack (webpack vs babel) and UI (uses React for other stuff in the app and I don't feel like setting up tooling - create-react-app did the tooling and I'm just using their build scripts.) So it's not really just the physics engine - it's having to convert physics + build pipe + UI to "something else" - and that's too much right now. Just trying to find a "pluggable" physics networking solution, and if it was just the physics engine, I might change. But after reading more, I'd have to rewrite the ENTIRE app - from the ground up - due to the isomorphic nature of `lance`. ALLL this is not meant to be judgemental - it's TOTALLY AWESOME what you've done here with `lance` - VERY impressed. I just can't "afford" to switch the existing codebase, so sorry!! Keep up the good work though! Seriously, awesome project here.

**Comment by namel** [comment]
Got it.  It is a lot of work switching from single-player to multiplayer.  From my experience with Asteroids, it seems like doubling the effort.
@AskingQuestions if you have the code lying around somewhere, I'll gladly include it.

**Comment by AskingQuestions** [comment]
> Got it. It is a lot of work switching from single-player to multiplayer. From my experience with Asteroids, it seems like doubling the effort.
> @AskingQuestions if you have the code lying around somewhere, I'll gladly include it.

@namel 

I just looked over the code (26 lines) and it barely implements the most basic MatterJS bodies. (Never got around to adding more.)
