### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by jstoeffler** [lance-gg/lance#78]
Hi there,

Thanks for this project, it looks like something we really need out there.
I was wondering if some members of your team would consider using typescript for this project ?

**Comment by namel** [comment]
Hi @jstoeffler do you suggest using Typescript for the lance implementation, or as an option that game developers can use?

In my personal experience, the addition of types did not prevent bugs, but did add significant verbosity to the code.

**Comment by namel** [comment]
Interesting output...  This is an opinionated topic, I suppose, meaning that my opinion isn't any better than anyone else's :)

I have a strong preference for minimalist code, but will reconsider in the future.
