### ISSUE TITLE
Bad import in THREEPhysicalObject

### ISSUE THREAD

**Issue by andrewkolos** [lance-gg/lance#99]
https://github.com/lance-gg/lance/blob/99f8cb8aca2b100bc56e775f23b2a6512317582b/src/serialize/THREEPhysicalObject.js#L1-L3

Is `PhysicalObject` supposed to be `PhysicalObject3D`? There is no `PhysicalObject` file in the directory.

Attempting to import `THREEPhysicalObject` results in an error:

``` Cannot find module './PhysicalObject' from 'THREEPhysicalObject.js'```

**Comment by namel** [comment]
The file `THREEPhysicalObject.js` should be removed.  I will remove it and release a patch.
